scrape:
  source_url: "https://xkcd.com/"
  scrape_pages_limit: 31   # -1 -> all pages
  request_retries: 3
  parallel : 10
database:
  db_path : "./pkg/database/database.json"
  temp_dir : "./pkg/database/"
  temp_folder_pattern : "responseTemp"
  temp_file_pattern : "response"